name: HACS validation
on:
    push:
        branches:
            - main
jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: "actions/checkout@v3"
            #- uses: "home-assistant/actions/hassfest@master"
            #- name: Checkout
            #  uses: actions/checkout@v2
            - name: HACS validation
              uses: "hacs/action@main"
              with:
                  category: "plugin"
